name: Build Module
on:
  push:
    branches: [ "*" ]
jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Install Nix
      uses: cachix/install-nix-action@v23

    - name: Cloning the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Building the module
      run: |
        # Set the git credentials
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        nix develop --command runLocalCi
        git checkout built
        git push --force origin built
      env:
        REPO_NAME: ${{github.event.repository.name}}
        REPO_OWNER: ${{github.repository_owner}}
    - uses: actions/checkout@v4
